name: chessgcn
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.1
  - pytorch-cuda=12.1
  - pyg
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - flask
  - pip
  - pip:
    - chess
